name: Run TESS-Atlas pipeline
on:
  workflow_dispatch: # Triggered manually
  # schedule:
  #   - cron: "0 0 * * 0" # Scheduled to run every Sunday at midnight (0:00)
#  push:
#      branches:
#        - master
#      paths:
#        - '.github/workflows/manager.yml' # run on changes to this file (for testing)


jobs:
  build:
    runs-on: nectar

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      - name: Trigger pipeline
        run: |
          # Add any environment setup commands here
          # For example, sourcing a virtual environment
          # source /path/to/your/virtualenv/bin/activate
          echo "start dir"
          pwd
          source ~/.bash_profile
          cd /mnt/storage/tess_atlas_pipeline/manager
          echo "new dir:"
          pwd
          echo "Running pipeline:"
          python pipeline.py tess_oct2_23 /mnt/storage/tess_atlas_webbuilder/source/objects/ --web-build-dir /mnt/storage/tess_atlas_webbuilder/ |& tee pipeline.log
        shell: bash

      # - name: Commit and Push Changes
      #   run: |
      #     git add data/*
      #     git commit -m "Update TIC cache"
      #     git push
      #   env:
      #     # Set the GitHub token to enable pushing back to the repository
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Cleanup
      #   uses: asilbek99/action-cleanup@v1.0
